# .readthedocs.yaml

version: 2

# Define the build tool
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

# Define Python dependencies
python:
  install:
    - method: pip
      path: .  # Install the package from the repository (setup reference)

# Sphinx-specific settings
sphinx:
  configuration: source/conf.py